vich_uploader:
    db_driver: orm

    mappings:
       products:
            uri_prefix: '%app.path.cours_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.cours_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true
